[package]
name = "transactions-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
csv = "1.1.6"
rust_decimal = "1.26.1"
serde = { version = "1.0.144", features = ["derive"] }
